// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';


var active = "active";

var background = "background";

var inactive = "inactive";

exports.active = active;
exports.background = background;
exports.inactive = inactive;
/* No side effect */
